EH6-cards-and-server
Legacy107/Everhunt pull request #4
Opened 2021-09-09 12:45 UTC by LeStolz

2021-09-11 11:09 UTC, Legacy107 requested changes

2021-09-11 11:09 UTC, Legacy107 commented on src/utils/MathUtil.gd
> +extends Object
Extends Reference for performance issue.

2021-09-11 11:09 UTC, Legacy107 commented on src/utils/MathUtil.gd
> +func calculate_pivot_rotation(Pivot, Target, Origin):
Make this a static func.

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/singletons/ServerHandler.gd
> +	var PlayerInstance = Player.instance()
Variable declaration should be at the top of the scope

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cards/Card.gd
> +func _init(card_info):
Rename card_info and variable to card_config and setting.

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/others/Player.gd
> +	for _id in range (cards_size):
Use array.resize() to fill cards with Null

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/others/Player.gd
> +var cards_size = 2
Is this a constant

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/others/Player.gd
> +export var GRAVITY = 3000
Set GRAVITY to ProjectSettings.get_setting("physics/2d/default_gravity")

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/others/Player.gd
> +onready var Flip = $Flip
Rename to Visual

2021-09-11 11:09 UTC, Legacy107 commented on src/scenes/Game.tscn
> +[ext_resource path="res://src/scripts/gamemodes/GameHandler.gd" type="Script" id=2]
Revert this change

2021-09-11 11:09 UTC, Legacy107 commented on src/utils/MathUtil.gd
> +	# Pivot is the pivot and the object whose rotation is calculated in this func
What does "the pivot and the object" mean?

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cardEffects/HomingMissile.gd
> +	ServerHandler.synchronize_unreliable(get_path(),
Break lines like this instead
```
ServerHandler.synchronize_unreliable(
    get_path(),
    "update_homing_missile_state",
    homing_missile_state
)
```

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cardEffects/HomingMissile.gd
> +	"position" : position
Add trailing comma

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cards/Card.gd
> +	"card_effect_instance_id" : 0
Add trailing comma

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cards/Card.gd
> +	Tween.interpolate_property(
Line break like this
```
Tween.interpolate_property(
    Pivot,
    "rotation",
    Pivot.rotation,
    MathUtil.calculate_pivot_rotation(Pivot, Mouse, Origin),
    card_swivel_dampening,
    Tween.TRANS_LINEAR,
    Tween.EASE_IN_OUT
)
```

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cards/Card.gd
> +remote func unsetup(_state):
Rename `unsetup` to `reset`

2021-09-11 11:09 UTC, Legacy107 commented on src/scripts/cards/Card.gd
> +		if _Player.cards[id] == "":
Change default value of _Player.cards[id] to null

2021-09-12 01:21 UTC, LeStolz commented on src/scripts/cards/Card.gd
> +func _init(card_info):
Rename "card_info" to "card_configs" and "variable" to "config"

2021-09-12 01:22 UTC, LeStolz commented on src/scripts/others/Player.gd
> +	for _id in range (cards_size):
No no no, we use PoolStringArray later so we change this later k bruh?

2021-09-12 01:23 UTC, LeStolz commented on src/scripts/others/Player.gd
> +var cards_size = 2
"cards_size" can be modified by the GameHandler if we so desire in the future.

2021-09-12 01:25 UTC, LeStolz commented on src/utils/MathUtil.gd
> +	# Pivot is the pivot and the object whose rotation is calculated in this func
English

2021-09-12 01:31 UTC, LeStolz commented on src/scripts/cards/Card.gd
> +		if _Player.cards[id] == "":
No no no We dun du dat here.

2021-09-12 03:01 UTC, LeStolz commented on src/scripts/cards/Card.gd
> +func _init(card_info):
Rename "card_info" to "card_settings" and "variable" to "setting"

2021-09-12 09:21 UTC, Legacy107 approved these changes
LGTM!

2021-09-12 09:27 UTC, merged