Docs
Legacy107/Everhunt pull request #5
Opened 2021-09-15 14:38 UTC by Legacy107

- Add docs for code flow
- Add docs for GameEvent, NodeUtil, MathUtil and MapInfo

2021-09-18 06:55 UTC, LeStolz requested changes
"gameFLow.jpg" should be "gameFlow.jpg" and may I ask why .jpg?

2021-09-18 06:55 UTC, LeStolz commented on docs/authors.rst
>  * sangpham2710
You can remove "* sangpham2710"

2021-09-18 06:55 UTC, LeStolz commented on docs/codeDocumentation.rst
> +    flow*
flowS?

2021-09-18 06:55 UTC, LeStolz commented on docs/flow.rst
> +.. image:: .\\images\\gameFLow.jpg
"gameFLow" should be "gameFlow"

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing singletons scripts
"singletons" should be "singleton"

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing files relating to tileset such as .tres files.
related?

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            [CTF] The postions of flag stations.
positions

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            [CTF] Emitted when a team capture the enemy's flag.
captureS

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            Emitted when a team score points.
scoreS

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
>          │    :term:`main.tscn`
Do we even have "main.tscn"?

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
>          Containing assets including images, sprites, sfx.
Change "including" to "such as" or "that are"

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing source code including scripts and scenes.
Change "including" to "such as" or "that are"

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing source code including scripts and scenes.
Shouldn't it be "source codes"?

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing scripts controlling player, abilities, game logics, networking, etc.
Maybe change "controlling" to "that control"

2021-09-18 06:55 UTC, LeStolz commented on docs/guidelines.rst
> +        Containing scripts controlling player, abilities, game logics, networking, etc.
"player" should be "players"

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            [CTF] Emitted when a flag is returned to its station.
Maybe you should say "to its team's station" to make it more obvious what the team_id param is for

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            Emitted when a team score points.
"Emitted when a team scores." is good enough and is better in that it make the score param more obvious

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +              The target that the Origin wants to point at.
"Origin" should be "Origin's look vector"

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +
Technically the Parameters above can be anything as long as they have position and global_position

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            - Origin (`Position2D <https://docs.godotengine.org/en/stable/classes/class_position2d.html>`_) –
Maybe note that the Origin MUST be a direct child of Pivot

2021-09-18 06:55 UTC, LeStolz commented on docs/references.rst
> +            The Pivot's rotation angle in radian.
I think you can omit the "angle" ._. and "rotation" is in radian by default so maybe dun need to specify that?

2021-09-18 07:03 UTC, Legacy107 commented
> "gameFLow.jpg" should be "gameFlow.jpg" and may I ask why .jpg?

JPEG format offers smaller file size

2021-09-18 07:05 UTC, Legacy107 commented on docs/guidelines.rst
>          │    :term:`main.tscn`
We will

2021-09-18 16:49 UTC, LeStolz requested changes
Change the goddamn "gameFLow" name properly

2021-09-18 16:49 UTC, LeStolz commented on docs/references.rst
> +              The target that the Origin's look vector wants to point at.
"the Origin" should be "Origin"

2021-09-18 16:49 UTC, LeStolz commented on docs/references.rst
> +              The Origin **must** be a direct child of the Pivot.
"The Origin" should be "Origin"

2021-09-18 16:49 UTC, LeStolz commented on docs/guidelines.rst
>          │    :term:`main.tscn`
"main" should be "Main"

2021-09-18 16:49 UTC, LeStolz commented on docs/guidelines.rst
>      main.tscn : file
"main" should be "Main"

2021-09-19 13:47 UTC, LeStolz commented on docs/references.rst
> +            Calculates the Pivot rotation such that Origin's look vector points at Target's global_position.
The Pivot's rotation

2021-09-19 15:05 UTC, LeStolz approved these changes

2021-09-19 15:06 UTC, LeStolz commented
LGTM!

2021-09-19 15:07 UTC, merged